export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

plugins=()

for file in $HOME/.config/zsh/plugins.d/**/*(Nx); do source $file; done

source $ZSH/oh-my-zsh.sh

for file in $HOME/.config/zsh/alias.d/**/*(Nx); do source $file; done
for file in $HOME/.config/zsh/zshrc.d/**/*(Nx); do source $file; done
for file in $HOME/.config/zsh/env.d/**/*(Nx); do source $file; done
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
