for file in $HOME/.config/zsh/plugins.d/**/*(Nx); do source $file; done
for file in $HOME/.config/zsh/alias.d/**/*(Nx); do source $file; done
for file in $HOME/.config/zsh/zshrc.d/**/*(Nx); do source $file; done
for file in $HOME/.config/zsh/env.d/**/*(Nx); do source $file; done

