---
- name: Setup k9s task for OS
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  ignore_errors: true
  vars:
    params:
      files:
        - "{{ansible_distribution|lower|replace(' ', '_')}}.yml"
        - "{{ansible_os_platform|lower|replace(' ', '_')}}.yml"
      paths:
        - "vars"

- import_tasks: debian.yml
  when: (ansible_facts['distribution'] == 'Ubuntu') or
    (ansible_facts['distribution'] == 'Debian')

- name: install k9s
  become: "{{ become_to_install }}"
  package:
    name: k9s
    state: present
  when: not ((ansible_facts['distribution'] == 'Ubuntu') or
    (ansible_facts['distribution'] == 'Debian'))

- name: Create config directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ k9s_config_dir }}"
    - "{{ k9s_config_dir }}/skins"

- name: Symlink configs
  file:
    src: "{{ role_path + '/files/' + item }}"
    dest: "{{ k9s_config_dir }}/{{ item }}"
    state: link
  loop:
    - "config.yaml"
    - "plugins.yaml"

- name: Download Everforest skin
  get_url:
    url: "https://raw.githubusercontent.com/derailed/k9s/master/skins/everforest-dark.yaml"
    dest: "{{ k9s_config_dir }}/skins/everforest-dark.yaml"

- include_tasks:
    file: roles/common/tasks/zsh-file-symlink.yml
