---
- hosts: all
  vars:
    ansible_os_platform: "mac"
  roles:
    - {role: 'homebrew', tags: 'homebrew'}
    - {role: 'zsh', tags: 'zsh'}
    - {role: 'git', tags: 'git'}
    - {role: 'fzf', tags: 'fzf'}
    - {role: 'ripgrep', tags: 'ripgrep'}
    - {role: 'neovim', tags: 'neovim'}
    - {role: 'alacritty', tags: 'alacritty'}
    - {role: 'asdf', tags: 'asdf'}
    - {role: 'tmux', tags: 'tmux'}

