---
- hosts: all
  vars:
    ansible_os_platform: "{{ os }}"
  roles:
    - {role: 'homebrew', tags: 'homebrew'}
    - {role: 'git', tags: 'git'}
    - {role: 'ellipsis', tags: 'ellipsis'}
    - {role: 'neovim', tags: 'neovim'}
