---
- name: Check if file exists
  stat:
    path: "/usr/local/bin/lazygit"
  register: already_installed

- name: Install lazygit
  become: true
  ansible.builtin.shell: |
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | \grep -Po '"tag_name": *"v\K[^"]*')
    curl -Lo /tmp/lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
    tar xf /tmp/lazygit.tar.gz /tmp/lazygit
    install /tmp/lazygit -D -t /usr/local/bin/
  when: not already_installed.stat.exists
