---
asdf_config_dir: ~/.asdf
zshrc_dir: ~/.config/zsh/zshrc.d
go_deps:
  - coreutils
  - curl
ruby_deps:
  - gcc
  - make
  - bzip2
  - openssl-devel
  - libyaml-devel
  - libffi-devel
  - readline-devel
  - zlib-devel
  - gdbm-devel
  - ncurses-devel

