---
- import_tasks: mac.yml
  when: ansible_os_platform|lower == 'mac'

- import_tasks: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'

- name: Get HOME directory
  set_fact:
    home_dir: "{{ lookup('env', 'HOME') }}"

- name: Create gitconfig
  ansible.builtin.template:
    src: "{{ role_path }}/files/gitconfig.jinja"
    dest: "{{ role_path}}/files/gitconfig.generated"

- name: Symlink config
  file:
    src: "{{ role_path }}/files/gitconfig.generated"
    dest: "~/.gitconfig"
    state: link
    force: yes
