---
- name: install git
  become: true
  package:
    name: git
    state: latest

- import_tasks: mac.yml
  when: ansible_os_platform|lower == 'mac'

- import_tasks: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'

- name: Get HOME directory
  set_fact:
    home_dir: "{{ lookup('env', 'HOME') }}"
      
- name: determine gpg install location
  ansible.builtin.shell: which gpg
  register: which_gpg_command

- name: register gpg bin fact
  set_fact:
    gpg_bin: "{{ which_gpg_command.stdout }}"

- name: Create gitconfig
  ansible.builtin.template:
    src: "{{ role_path }}/files/gitconfig.j2"
    dest: "~/.gitconfig"

