---
- name: Check if homebrew already installed
  stat: 
    path: /usr/local/bin/brew
  register: brew_location

- name: Pull homebrew install ruby script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install
    dest: "{{ homebrew_install_script_loc }}"
  when: not brew_location.stat.exists

- name: install homebrew
  shell: /usr/bin/ruby "{{ homebrew_install_script_loc }}" >> /dev/null
  when: not brew_location.stat.exists

- name: Remove homebrew install script
  file:
    state: absent
    path: "{{ homebrew_install_script_loc }}"

