---
- name: Pull homebrew install ruby script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install
    dest: /tmp/homebrew_install.rb

- name: install homebrew
  shell: /usr/bin/ruby "/tmp/homebrew_install.rb" >> /dev/null
