---
- name: install light
  become: true
  package:
    name: light
    state: present

- name: Assign group video to current user
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    group: video
