---
- name: install tmux
  become: true
  package:
    name: tmux
    state: latest

- import_tasks: mac.yml
  when: ansible_os_platform|lower == 'mac'

- import_tasks: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'

- import_tasks: debian.yml
  when: ansible_facts['distribution'] == 'Debian'

- include_tasks:
    file: roles/common/tasks/zsh-file-symlink.yml

- name: create config directory
  file:
    path: "{{ tmux_config_dir }}"
    state: directory

- name: Create .tmux.conf
  ansible.builtin.template:
    src: "{{ role_path }}/files/tmux.conf.j2"
    dest: "~/.tmux.conf"

- name: find tmux config files
  find:
    paths: "{{ role_path + '/files' }}"
    patterns: 
      - "{{ tmux_platform_config }}"
      - "tmux.common.conf"
    depth: 1
    file_type: file
  register: tmux_config_files

- name: Symlink config files
  file:
    src: "{{ item.path }}"
    dest: "{{ tmux_config_dir }}/{{ item.path.split('/')[-1] }}"
    state: link
  loop: "{{ tmux_config_files.files }}"

