---
- name: find zsh config files
  find:
    paths: "{{ role_path + '/files/' + item + '.d' }}"
    depth: 1
    file_type: any
  loop:
    - alias
    - env
    - profile
    - zshrc
    - plugins
  register: config_files

- name: Symlink zsh config scripts
  file:
    src: "{{ item.path }}"
    dest: "~/.config/zsh/{{ item.path.split('/')[-2] }}/{{ item.path.split('/')[-1] }}"
    state: link
  loop: "{{ config_files.results | map(attribute='files') | list | flatten(levels=1) }}"

