---
# exa unmaintained. Need to move to eza
# zypper ar https://download.opensuse.org/tumbleweed/repo/oss/ factory-oss
# zypper in eza
- name: install eza
  become: "{{ become_to_install }}"
  package:
    name: eza
    state: latest

- include_tasks:
    file: roles/common/tasks/zsh-file-symlink.yml
