---
- name: install alacritty
  become: true
  package:
    name: alacritty
    state: latest

- name: Create alacritty config directory
  file:
    path: "~/.config/alacritty"
    state: directory

- name: Symlink config
  file:
    src: "{{ role_path }}/files/alacritty.yml"
    dest: "~/.config/alacritty/alacritty.yml"
    state: link

- name: download term info
  shell: curl -sSL https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info -o /tmp/alacritty.terminfo
  args:
    executable: /bin/zsh

- name: install alacritty term info
  shell: tic -x /tmp/alacritty.terminfo
  args:
    executable: /bin/zsh
