---
- name: Setup gpg task for OS
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution|lower}}.yml'
        - '{{ansible_os_platform|lower}}.yml'
      paths:
        - 'vars'

- name: install gpg
  become: true
  package:
    name: "{{ packages }}"
    state: latest

- include_tasks:
    file: roles/common/tasks/zsh-file-symlink.yml
