---
- name: Setup gpg task for OS
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ansible_distribution|lower|replace(' ', '_')}}.yml"
        - "{{ansible_os_platform|lower|replace(' ', '_')}}.yml"
      paths:
        - 'vars'

- name: install fd
  become: true
  package:
    name: "{{ fdPackages }}"
    state: latest

- include_tasks:
    file: roles/common/tasks/zsh-file-symlink.yml

