---
- import_tasks: mac.yml
  when: ansible_os_platform|lower == 'mac'

- import_tasks: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'

- import_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Create config directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.local/share/nvim/site/pack/packer/start
    - "{{ nvim_config_dir }}/bundle"
    - "{{ nvim_config_dir }}/autoload"

      #- name: clone packer
      #  ansible.builtin.git:
      #    repo: https://github.com/wbthomason/packer.nvim
      #    depth: 1
      #    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim

      #- name: Install vim-plug
      #  get_url:
      #    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      #    dest: "{{ nvim_config_dir }}/autoload/plug.vim"
      #    force: yes

- name: find
  find:
    paths: "{{ role_path + '/files' }}"
    depth: 1
    file_type: any
  register: nvim_role_files

- name: Symlink config
  file:
    src: "{{ item.path }}"
    dest: "{{ nvim_config_dir }}/{{ item.path.split('/')[-1] }}"
    state: link
  loop: "{{ nvim_role_files.files }}"

- name: Install plugins
  shell: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

    #- name: Install plugins
    #  shell: nvim "+silent! PlugInstall" +qall\!
