---
- import_tasks: mac.yml
  when: ansible_os_platform|lower == 'mac'

- import_tasks: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'

- import_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Create config directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.local/share/nvim/site/pack/packer/start
    - "{{ nvim_config_dir }}/bundle"
    - "{{ nvim_config_dir }}/autoload"

- name: find
  find:
    paths: "{{ role_path + '/files' }}"
    depth: 1
    file_type: any
  register: nvim_role_files

- name: Symlink config
  file:
    src: "{{ item.path }}"
    dest: "{{ nvim_config_dir }}/{{ item.path.split('/')[-1] }}"
    state: link
  loop: "{{ nvim_role_files.files }}"

- name: Install plugins
  shell: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

