---
- import_tasks: mac.yml
  when: ansible_os_platform|lower == 'mac'

- name: Create config directory
  file: path=~/.config/nvim/bundle state=directory

- name: install nvim dot files from ellipsis
  command: ellipsis install "{{ ellipsis_nvim_dot_repo }}"
