---
- name: set fonts directory mac
  ansible.builtin.set_fact:
    fonts_dir: ~/Library/Fonts
  when: ansible_os_platform|lower == 'mac'

- name: set fonts directory linux
  ansible.builtin.set_fact:
    fonts_dir: ~/.local/share/fonts
  when: ansible_os_platform|lower != 'mac'

- import_tasks: fedora.yml
  when: ansible_facts['distribution'] == 'Fedora'

- name: make Hack Nerd Font directory
  file:
    path: "{{ fonts_dir }}/nerd-fonts/Hack"
    state: directory

- name: make fontconfig directory
  file:
    path: ~/.config/fontconfig/conf.d
    state: directory

- name: Download Hack Nerd Font
  get_url:
    url: "{{ item.url }}"
    dest: "{{ fonts_dir }}/nerd-fonts/Hack/{{ item.fileName }}"
  loop:
    - fileName: "hackRegularNerdFontCompleteMono.ttf"
      url: "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Regular/HackNerdFontMono-Regular.ttf?raw=true"
    - fileName: "hackItalicNerdFontCompleteMono.ttf"
      url: "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Italic/HackNerdFontMono-Italic.ttf?raw=true"
    - fileName: "hackBoldItalicNerdFontCompleteMono.ttf"
      url: "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/BoldItalic/HackNerdFontMono-BoldItalic.ttf?raw=true"
    - fileName: "hackBoldNerdFontCompleteMono.ttf"
      url: "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Bold/HackNerdFontMono-Bold.ttf?raw=true"

- name: Download Nerd Fonts config
  get_url:
    url: https://raw.githubusercontent.com/ryanoasis/nerd-fonts/refs/heads/master/10-nerd-font-symbols.conf
    dest: ~/.config/fontconfig/conf.d/10-nerd-font-symbols.conf

- name: update fc cache
  become: true
  command: fc-cache -rv
